### ISSUE TITLE
Bamboo

### ISSUE THREAD

**Issue by 3Lord3** [Pwn9/PwnPlantGrowth#13]
I have bamboo growing in all biomes, and also kicks out when using bone meal on it due to "Packet processing error"
I tried removing GrowthDark and DeathDark, but it didn't help

Config: https://pastebin.com/2WuPP7E9

Perhaps this is because the plugin does not use BAMBOO_SAPLING

**Comment by galacticwarrior9** [comment]
OP forgot to include the actual error, so here it is below: 

```
[15:26:20] [Server thread/ERROR]: Error whilst processing packet net.minecraft.server.v1_16_R3.PacketPlayInUseItem@7672ccd4 for Daynshi[/49.145.228.37:39850]
java.lang.IllegalArgumentException: Cannot get property BlockStateInteger{name=stage, clazz=class java.lang.Integer, values=[0, 1]} as it does not exist in Block{minecraft:air}
	at net.minecraft.server.v1_16_R3.IBlockDataHolder.get(IBlockDataHolder.java:95) ~[patched_1.16.5.jar:git-Purplane-"b5b6595"]
	at net.minecraft.server.v1_16_R3.BlockBamboo.a(BlockBamboo.java:152) ~[patched_1.16.5.jar:git-Purplane-"b5b6595"]
	at net.minecraft.server.v1_16_R3.ItemBoneMeal.a(ItemBoneMeal.java:56) ~[patched_1.16.5.jar:git-Purplane-"b5b6595"]
	at net.minecraft.server.v1_16_R3.ItemBoneMeal.applyBonemeal(ItemBoneMeal.java:25) ~[patched_1.16.5.jar:git-Purplane-"b5b6595"]
	at net.minecraft.server.v1_16_R3.ItemBoneMeal.a(ItemBoneMeal.java:16) ~[patched_1.16.5.jar:git-Purplane-"b5b6595"]
	at net.minecraft.server.v1_16_R3.ItemStack.placeItem(ItemStack.java:234) ~[patched_1.16.5.jar:git-Purplane-"b5b6595"]
	at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:566) ~[patched_1.16.5.jar:git-Purplane-"b5b6595"]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1664) ~[patched_1.16.5.jar:git-Purplane-"b5b6595"]
	at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.16.5.jar:git-Purplane-"b5b6595"]
	at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.16.5.jar:git-Purplane-"b5b6595"]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43) ~[patched_1.16.5.jar:git-Purplane-"b5b6595"]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Purplane-"b5b6595"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Purplane-"b5b6595"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Purplane-"b5b6595"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Purplane-"b5b6595"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1212) ~[patched_1.16.5.jar:git-Purplane-"b5b6595"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1205) ~[patched_1.16.5.jar:git-Purplane-"b5b6595"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Purplane-"b5b6595"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1181) ~[patched_1.16.5.jar:git-Purplane-"b5b6595"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1025) ~[patched_1.16.5.jar:git-Purplane-"b5b6595"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.5.jar:git-Purplane-"b5b6595"]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

It can also lead to a fatal server crash. See also [the Spigot thread](https://www.spigotmc.org/threads/pwnplantgrowth.284470/page-4) for similar reports.

```
[15:28:51] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_16_R3.ReportedException: Exception while ticking
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1456) ~[patched_1.16.5.jar:git-Purplane-"b5b6595"]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:388) ~[patched_1.16.5.jar:git-Purplane-"b5b6595"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1289) ~[patched_1.16.5.jar:git-Purplane-"b5b6595"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1015) ~[patched_1.16.5.jar:git-Purplane-"b5b6595"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.5.jar:git-Purplane-"b5b6595"]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IllegalArgumentException: Cannot get property BlockStateInteger{name=stage, clazz=class java.lang.Integer, values=[0, 1]} as it does not exist in Block{minecraft:air}
	at net.minecraft.server.v1_16_R3.IBlockDataHolder.get(IBlockDataHolder.java:95) ~[patched_1.16.5.jar:git-Purplane-"b5b6595"]
	at net.minecraft.server.v1_16_R3.BlockBamboo.a(BlockBamboo.java:152) ~[patched_1.16.5.jar:git-Purplane-"b5b6595"]
	at net.minecraft.server.v1_16_R3.ItemBoneMeal.a(ItemBoneMeal.java:56) ~[patched_1.16.5.jar:git-Purplane-"b5b6595"]
	at net.minecraft.server.v1_16_R3.IDispenseBehavior$19.a(IDispenseBehavior.java:646) ~[patched_1.16.5.jar:git-Purplane-"b5b6595"]
	at net.minecraft.server.v1_16_R3.DispenseBehaviorItem.dispense(DispenseBehaviorItem.java:17) ~[patched_1.16.5.jar:git-Purplane-"b5b6595"]
	at net.minecraft.server.v1_16_R3.BlockDispenser.dispense(BlockDispenser.java:60) ~[patched_1.16.5.jar:git-Purplane-"b5b6595"]
	at net.minecraft.server.v1_16_R3.BlockDispenser.tickAlways(BlockDispenser.java:86) ~[patched_1.16.5.jar:git-Purplane-"b5b6595"]
	at net.minecraft.server.v1_16_R3.BlockBase$BlockData.a(BlockBase.java:622) ~[patched_1.16.5.jar:git-Purplane-"b5b6595"]
	at net.minecraft.server.v1_16_R3.WorldServer.b(WorldServer.java:1349) ~[patched_1.16.5.jar:git-Purplane-"b5b6595"]
	at com.destroystokyo.paper.server.ticklist.PaperTickList.tick(PaperTickList.java:309) ~[patched_1.16.5.jar:git-Purplane-"b5b6595"]
	at net.minecraft.server.v1_16_R3.TickListServer.b(TickListServer.java:47) ~[patched_1.16.5.jar:git-Purplane-"b5b6595"]
	at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:942) ~[patched_1.16.5.jar:git-Purplane-"b5b6595"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1440) ~[patched_1.16.5.jar:git-Purplane-"b5b6595"]
	... 5 more
[15:28:51] [Server thread/ERROR]: 	Cause of unexpected exception was
java.lang.IllegalArgumentException: Cannot get property BlockStateInteger{name=stage, clazz=class java.lang.Integer, values=[0, 1]} as it does not exist in Block{minecraft:air}
	at net.minecraft.server.v1_16_R3.IBlockDataHolder.get(IBlockDataHolder.java:95) ~[patched_1.16.5.jar:git-Purplane-"b5b6595"]
	at net.minecraft.server.v1_16_R3.BlockBamboo.a(BlockBamboo.java:152) ~[patched_1.16.5.jar:git-Purplane-"b5b6595"]
	at net.minecraft.server.v1_16_R3.ItemBoneMeal.a(ItemBoneMeal.java:56) ~[patched_1.16.5.jar:git-Purplane-"b5b6595"]
	at net.minecraft.server.v1_16_R3.IDispenseBehavior$19.a(IDispenseBehavior.java:646) ~[patched_1.16.5.jar:git-Purplane-"b5b6595"]
	at net.minecraft.server.v1_16_R3.DispenseBehaviorItem.dispense(DispenseBehaviorItem.java:17) ~[patched_1.16.5.jar:git-Purplane-"b5b6595"]
	at net.minecraft.server.v1_16_R3.BlockDispenser.dispense(BlockDispenser.java:60) ~[patched_1.16.5.jar:git-Purplane-"b5b6595"]
	at net.minecraft.server.v1_16_R3.BlockDispenser.tickAlways(BlockDispenser.java:86) ~[patched_1.16.5.jar:git-Purplane-"b5b6595"]
	at net.minecraft.server.v1_16_R3.BlockBase$BlockData.a(BlockBase.java:622) ~[patched_1.16.5.jar:git-Purplane-"b5b6595"]
	at net.minecraft.server.v1_16_R3.WorldServer.b(WorldServer.java:1349) ~[patched_1.16.5.jar:git-Purplane-"b5b6595"]
	at com.destroystokyo.paper.server.ticklist.PaperTickList.tick(PaperTickList.java:309) ~[patched_1.16.5.jar:git-Purplane-"b5b6595"]
	at net.minecraft.server.v1_16_R3.TickListServer.b(TickListServer.java:47) ~[patched_1.16.5.jar:git-Purplane-"b5b6595"]
	at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:942) ~[patched_1.16.5.jar:git-Purplane-"b5b6595"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1440) ~[patched_1.16.5.jar:git-Purplane-"b5b6595"]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:388) ~[patched_1.16.5.jar:git-Purplane-"b5b6595"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1289) ~[patched_1.16.5.jar:git-Purplane-"b5b6595"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1015) ~[patched_1.16.5.jar:git-Purplane-"b5b6595"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.5.jar:git-Purplane-"b5b6595"]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by msudol** [comment]
Minecraft server version?

**Comment by galacticwarrior9** [comment]
Tested on Paper 1.16.5 Build 503. 

I included a more detailed report, with reproduction steps, on their issue tracker (https://github.com/PaperMC/Paper/issues/5280)

**Comment by 3Lord3** [comment]
Server: git-Yatopia-6 (MC: 1.16.5)
I get no errors in the console (probably because I have not enabled debug_log)

Also, the bamboo grows incorrectly by itself. Despite the fact that I specified its growth only in the jungle, it grows at least 1 block in any biome. Because of this, it can still be grown

**Comment by msudol** [comment]
Tested it out, spigot and paper latest versions, confirm there is a bug..  paper kicks players out, spigot handles the error just fine. Clearly a result of PwnPlantGrowth but no trace to the PPG plugin in the stack trace which is odd...  making some adjustments to the plugin and testing but so far I can't seem to fix it... it honestly seems to be an error resulting from cancelling the BlockSpreadEvent on the BAMBOO block when using Bonemeal... something else in the spigot/paper code appears to be following up on the event with an ASYNC task and not realizing the event has been cancelled....   don't think this is my bug to fix - but I'll keep researching.

**Comment by DreamPhreak** [comment]
This has been fixed. Update Paper to build #562 or newer. [Commit Reference](https://github.com/PaperMC/Paper/commit/ae15e85da4317fc7dc118648cae1964db33129a9)
